---

 - name: Ensure PPTP client packages are installed
   apt: name="{{ item }}" state=installed update_cache=yes cache_valid_time=86400
   with_items: "{{ pptp_packages }}"

   # See http://askubuntu.com/questions/269399/failed-to-connect-to-pptp-vpn-server-on-ubuntu
 - name: Ensure nf_conntrack_pptp kernel module is loaded
   modprobe: name=nf_conntrack_pptp state=present

 - name: Setup present peers
   template: src=peer.j2 dest="/etc/ppp/peers/{{ item.name }}" owner=root group=root mode=0600
   with_items: "{{ pptp_peers_present }}"

 - name: Setup absent peers
   file: name="/etc/ppp/peers/{{ item }}" state=absent
   with_items: "{{ pptp_peers_absent }}"

 - name: Setup /etc/ppp/chap-secrets
   template: src=chap-secrets.j2 dest=/etc/ppp/chap-secrets owner=root group=root mode=0600

 - name: Setup routes on tunnel up
   template: src=01-pptp-routes-up.j2 dest=/etc/ppp/ip-up.d/01-pptp-routes-up owner=root group=root mode=0751

 - name: Start tunnels if configured
   shell: "/usr/bin/pon {{ item.name }}"
   with_items: "{{ pptp_peers_present }}"
   when: pptp_autostart_present_peers
